hash-format = "sha256"

[[files]]
file = "global_packs/required_data/AllTheMons Release 2.3.zip"
hash = "fe6e3fbf4d9bd079ed20b3d5665487db14571493975cc7b657d86edbf590c445"

[[files]]
file = "global_packs/required_data/Angel_Islands_1.0.1.zip"
hash = "b709ca09d23e49a4f6b316ad79277a10acbbb01e8eb6c9219ca246b1353d073c"

[[files]]
file = "mods/a-man-with-plushies.pw.toml"
hash = "f47e44843ba6aff3e320fa0b7307060df8924d467eab94a5587fd8694b92c7ec"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
hash = "b4160f327578ee994907c217b8de09e2c4377b5735b12ad56d91cb1a08ddd62d"
metafile = true

[[files]]
file = "mods/aether.pw.toml"
hash = "5e62bb12eb55e4575d1ca5e3570b5cc18473138973c80ac7093e61e459339db1"
metafile = true

[[files]]
file = "mods/air-balloons.pw.toml"
hash = "70743439137808f1d50fa0b2203d392cccf24a1751aa328201e4274260a52800"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "5724ca10bd6d37de46834ab762a46f9ce09175f0a4fa0e2ab633846067940c03"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ea336d25c3e21ef168aec20e1ea470c96949ad29632646ee8e8ab0d74b4bbfc9"
metafile = true

[[files]]
file = "mods/ars-nouveau.pw.toml"
hash = "c620b91abf14510baca9164bdd1ab39b8f6390c080c7a8f67e66b7fa25b515b5"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "146dd7165c696bfa10cd8e6fa90dd5b2578244ecd35e041557b76b0cff2d0fa6"
metafile = true

[[files]]
file = "mods/better-combat.pw.toml"
hash = "3b25384acb368599971dd72d3fa48f5449552e6f732d5c25caee154926a447b1"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "8fde54624913d86f1176cd1086fa485f1a872573dac144347c57cab76596b715"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/cobblemon.pw.toml"
hash = "e3cb1eb238192071af93f764e3ff2c493f4f437802bb56273f664bafdea13f1d"
metafile = true

[[files]]
file = "mods/crawl.pw.toml"
hash = "349b56aa9ea8284fb89e880941d319ce52e50e51d63084472ea93493cff105b7"
metafile = true

[[files]]
file = "mods/create-central-kitchen.pw.toml"
hash = "c63270ea90901dbb5c515ad2ca574e3d390fea86c22c239e30da919625be0741"
metafile = true

[[files]]
file = "mods/create-cobblemon-balls-overhaul.pw.toml"
hash = "93cca7488736da21ec9e86e79e0578eafb7e77889cb032d1c810231152e086d9"
metafile = true

[[files]]
file = "mods/create-confectionery.pw.toml"
hash = "85bfeee744eff6e3cb9146da32407874d569237298072c4455224566e322e476"
metafile = true

[[files]]
file = "mods/create-dragons-plus.pw.toml"
hash = "39262522d1617ae4dc5d7c862cf4e457fdbcb948de13425b9a598cc5864a459f"
metafile = true

[[files]]
file = "mods/create-dreams-and-desires.pw.toml"
hash = "32956e0b85a4631a5c2091bbd64387978970e83c3d6f7654a3a4a8b59ddff0cc"
metafile = true

[[files]]
file = "mods/create-encased.pw.toml"
hash = "b6003ddf6db6b3a55a748bdecd1c5b2cf8be6b178a2932772c569457e3c96fd5"
metafile = true

[[files]]
file = "mods/create-enchantable-machinery.pw.toml"
hash = "1f672d49cbe7a73c3d1da775e30754d0ac9d5368cc2ff5bcadf26d144e82a729"
metafile = true

[[files]]
file = "mods/create-enchantment-industry-plus.pw.toml"
hash = "1165e2f94bf27b41cf7ff24e6e4a217bd661755f2b894db26e2ec1eafe752231"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "60231e01fc1a64f3f0b155738bf5f56e9cb0f84d930b04aac83858357c4deaaf"
metafile = true

[[files]]
file = "mods/create-framed.pw.toml"
hash = "bed535a9a5636585ef25b31038ebdb6cad1967e4f1e1de8bcb773bc6c569ad2a"
metafile = true

[[files]]
file = "mods/create-fuel-motor.pw.toml"
hash = "df7fef76989aab54a3fdd8bfe35967eda3bcb0dc2764b8f19c0f1e75e16df909"
metafile = true

[[files]]
file = "mods/create-let-the-adventure-begin.pw.toml"
hash = "0bd9f63d607ad6198a00a36a743ac64e0f57aa684acc5319a61382a819fd1ca6"
metafile = true

[[files]]
file = "mods/create-man-of-many-planes.pw.toml"
hash = "2cc0e1f0bf03986c8ff89e27035ce0a4d23670c5d49c7a334ee2914495b9ab5e"
metafile = true

[[files]]
file = "mods/create-power-loader.pw.toml"
hash = "ee76dbe108ebf5cf68047f60ecabee5aeb029015253dc82c007b941a6d6cfcdf"
metafile = true

[[files]]
file = "mods/create-qol.pw.toml"
hash = "a41f0a61345cd4f5e510a01977c15faa4365d2ad7bc0508207d7f879f8b56e19"
metafile = true

[[files]]
file = "mods/create-sifting.pw.toml"
hash = "97019bb26e1b0a861907edf8bb10ad4ba783651b5615ccbee10ca5c253b397f1"
metafile = true

[[files]]
file = "mods/create-stock-bridge.pw.toml"
hash = "9293bf6d4b52a44f6209a4f4023dfcc19a6507889faf81644140e1a9ec6ed220"
metafile = true

[[files]]
file = "mods/create-structures-arise.pw.toml"
hash = "e6f728d6f85376948b2241ef71ea6a6e47de5b2e390f5f46e3dddbd05a2a1875"
metafile = true

[[files]]
file = "mods/create-stuff-additions.pw.toml"
hash = "7bdf3b6cbe0579a034372ce1eec83e3c1888134f19beb6b17fbf2005706453be"
metafile = true

[[files]]
file = "mods/create-trading-floor.pw.toml"
hash = "67422fb0ab5a5ae646fb99077e83282c2e13e29749611bcb64bbbe02ccdb644a"
metafile = true

[[files]]
file = "mods/create-ultimate-factory.pw.toml"
hash = "391f875058b29709daf39840494db640bfe7a35262f45b81689df8af350cba82"
metafile = true

[[files]]
file = "mods/create-vibrant-vaults.pw.toml"
hash = "960645d7f385081b108208e58bbbdfc6b93288b7bd7da90e6f229a57b237234a"
metafile = true

[[files]]
file = "mods/create-winery.pw.toml"
hash = "cfc8dbfed63284c828a8141003a5a34ea58b8c9d62d5c520d4b42d3e65858c7e"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "a4c8371232d9f542b180c7bd7e30d84b9e958b97b24af5dde0759ab8e511fb8e"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "bffb086ccb18831669912bfca626b405a180555c3e395301089d3104336dbba8"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "36debf7653e95a855b4fedacc19027cf2e01960fc0b6d55ef2ffbffbcb455690"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "d3c9b48d7caa2ed964e5d1a4dab1da5655c63f0a7e4a59231c4369be7ffc30e1"
metafile = true

[[files]]
file = "mods/exposure.pw.toml"
hash = "7bebff0ec65bcef0fc44358719d3b9ccc6e0d658ea49c07b24c3d9416e4576f2"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "867a029a8bed75bea2fb02e5186730db46ec01f970d0bdb266c6897074c16177"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "548cf9b25748105c70af57d4f169f4f8ea9c47c1ec6ec9cae9cbe264bdf31754"
metafile = true

[[files]]
file = "mods/geophilic.pw.toml"
hash = "87d16e6f43df61a8fb025a9977343bc2f026570d198f48d82ef087be0d9e29eb"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "dbd756dd9bb17e6ecebcf2d7052a67a2da1c7dd378bc2089bc154916080fe031"
metafile = true

[[files]]
file = "mods/globalpacks.pw.toml"
hash = "f426f827dc4ba8d6b31715054f74f003259aa2db9d5d86af67d0f5402160bd0f"
metafile = true

[[files]]
file = "mods/guideme.pw.toml"
hash = "3d0defaa05f249638a4f43b84ae20294409b90b9f68b36e7a9aa771997129229"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "019fea93516a470bbcad284dd0cbad6f4e2914d96221c86e3f87c12fe6321e10"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
hash = "80b8f5ac81313635f3829c0bfc1be0c82190cd5eeb2bd0f74039548f5d300ecc"
metafile = true

[[files]]
file = "mods/item-highlighter.pw.toml"
hash = "9163b758163681f75e2048c798be880c50392684b127d7d87f42ea588deceb62"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "652900870d343dda5683456934ca76bf176ea54da73d9883d8a13c9b3cae2fac"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "44634200be079994523f61e1a4b2878f4d2e1b59d52378391aa81192b1d15bf1"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "ae66866cd5017cb9e2fb7d45718cfcf041f3aa93484ec4a5cd3fdd894651e53a"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "0a983d1515e1713d1a0ae7738091909101c368be2726a446e4ca29c62fe555c2"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "b8ce87d9a7164676e68e69e9e6706cd6e9123b1fe740612b1ba39b43ce8675ef"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "4fb1a31fed2b085e5f798c2a199fec357490f1da72451a612334776111d80d15"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "28cd260c71c34d01f59ea210af1031e94d98b4d6bd72d5a153955ce754c9a76f"
metafile = true

[[files]]
file = "mods/man-of-many-planes.pw.toml"
hash = "d887c005b64a36e1ab515d2fc6a35531b665ff7f4964b7068a01d3a136925641"
metafile = true

[[files]]
file = "mods/mechanicals-lib.pw.toml"
hash = "e38ad2bf4e13c926930ed0f12519fd68bdcdf4e8aa54c906810ec34fc6c47a5d"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
hash = "f376fde0de0f58f52d9e49617907549bfc833979a9c21e8668839bae63b822f2"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6bc414cc0f2d4c078fe83f384d786343f701f371d657c5279b5b0df1595804bd"
metafile = true

[[files]]
file = "mods/oritech.pw.toml"
hash = "9f8425d11a88ff7df5fd0e4850e3aa76d4784435283b9cc941ccf6ae7473aa37"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "b30bf3e10fdb43cb451091d4cc8ff88081895686c492c1bbff50ce0c74a3e85b"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "c83705becd548879473132552de960f9d5975fa0edaeeb2d4665a4e35457423e"
metafile = true

[[files]]
file = "mods/pneumaticcraft-repressurized.pw.toml"
hash = "f4ba7e9b81e7519c5a91b0a8d8401f19156bafb97b61d5837ee57fb3d0d65fc6"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "74c4147419e31244a156285fc030ca773e7f35c69a04ad15cc5af68aa4db72b5"
metafile = true

[[files]]
file = "mods/serene-seasons.pw.toml"
hash = "73b1e4f6608fcd396acc3e4e7aa753d314c8810ef4caf831ed93d9932d93f896"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "593fa7b30ab016aa45be07bd6bef3a9f160ed0f24689850d60bf84995d69b843"
metafile = true

[[files]]
file = "mods/stitch.pw.toml"
hash = "3297ddc42341656ac272d21e3fcdb7c2d1cc516c73c2e1bd5c08edfd64b9304a"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "7b94f0b60ec6eb8507c78bcc88b6e51e6f9c37963bf388fa501acaf56b3714e0"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "da7ee99189ad35aac094919fe33cac647d98533b23c228f10d4811f08989e2b8"
metafile = true

[[files]]
file = "mods/terraphilic.pw.toml"
hash = "2adf25ec00711d16b41c883e468df80e55448740b300d694364dd50744d76605"
metafile = true

[[files]]
file = "mods/the-twilight-forest.pw.toml"
hash = "bbd1d4b8b1562f98c9247a29de80b0ba5447dda5b549a8b4ee732c38925b784b"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "83c2f33a6656799f209ee75d63da20c4e692202371a221fd853792dad6113d7e"
metafile = true
