name = "Modpack"
author = "Solariity & kapsikkum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8edfef2bb02c444602693f75772ccf7df7fe2a208efa0442060e01e48e51002f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[options]
acceptable-game-versions = []
